### PR TITLE
Use predicates 2 to drop unmainted diff library

### PR DESCRIPTION
**Pull request by matze**
See https://rustsec.org/advisories/RUSTSEC-2020-0095.

### CODE REVIEW

**Comment by matze** [comment]
@Hywan is this crate unmaintained?

**Comment by Hywan** [comment]
This crate is maintained. I’m just off for a couple of days (something we call _holidays_ ;-)). Will merge it next week.

Thanks for the PR!

**Comment by matze** [comment]
> something we call _holidays_ ;-)

Haha, no pressure :-) Have fun!

**Comment by Hywan** [comment]
v0.1.7 released, thanks for the PR!

**Comment by matze** [comment]
Much appreciated, thanks!

**Pull request merged**
